---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-commons

---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard

---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx
